version: '2.0'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: PROPIEDADES
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  web:
    image: adminer
    restart: always
    ports:
      - 80:8080
