package entidades;
// Generated 19-feb-2020 19:21:03 by Hibernate Tools 4.3.1



/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private int codigo;
     private Float porcentajeBeneficio;
     private String nombre;

    public Autor() {
    }

	
    public Autor(int codigo) {
        this.codigo = codigo;
    }
    public Autor(int codigo, Float porcentajeBeneficio, String nombre) {
       this.codigo = codigo;
       this.porcentajeBeneficio = porcentajeBeneficio;
       this.nombre = nombre;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Float getPorcentajeBeneficio() {
        return this.porcentajeBeneficio;
    }
    
    public void setPorcentajeBeneficio(Float porcentajeBeneficio) {
        this.porcentajeBeneficio = porcentajeBeneficio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


