package entidades;
// Generated 16-feb-2020 0:32:35 by Hibernate Tools 4.3.1



/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private int codigo;
     private Float porcentajeBeneficio;

    public Autor() {
    }

	
    public Autor(int codigo) {
        this.codigo = codigo;
    }
    public Autor(int codigo, Float porcentajeBeneficio) {
       this.codigo = codigo;
       this.porcentajeBeneficio = porcentajeBeneficio;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Float getPorcentajeBeneficio() {
        return this.porcentajeBeneficio;
    }
    
    public void setPorcentajeBeneficio(Float porcentajeBeneficio) {
        this.porcentajeBeneficio = porcentajeBeneficio;
    }




}


