package entidades;
// Generated 16-feb-2020 0:32:35 by Hibernate Tools 4.3.1



/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private String usuario;
     private String password;

    public Cuenta() {
    }

    public Cuenta(String usuario, String password) {
       this.usuario = usuario;
       this.password = password;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


