package entidades;
// Generated 19-feb-2020 19:21:03 by Hibernate Tools 4.3.1



/**
 * Escribe generated by hbm2java
 */
public class Escribe  implements java.io.Serializable {


     private EscribeId id;
     private Float beneficioAutor;

    public Escribe() {
    }

	
    public Escribe(EscribeId id) {
        this.id = id;
    }
    public Escribe(EscribeId id, Float beneficioAutor) {
       this.id = id;
       this.beneficioAutor = beneficioAutor;
    }
   
    public EscribeId getId() {
        return this.id;
    }
    
    public void setId(EscribeId id) {
        this.id = id;
    }
    public Float getBeneficioAutor() {
        return this.beneficioAutor;
    }
    
    public void setBeneficioAutor(Float beneficioAutor) {
        this.beneficioAutor = beneficioAutor;
    }




}


