package entidades;
// Generated 16-feb-2020 0:32:35 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private String isbn;
     private String titulo;
     private String portada;
     private Date fechaPublicacion;
     private Float precio;
     private String nifAutorPrincipal;
     private String propietario;

    public Libro() {
    }

	
    public Libro(String isbn, String propietario) {
        this.isbn = isbn;
        this.propietario = propietario;
    }
    public Libro(String isbn, String titulo, String portada, Date fechaPublicacion, Float precio, String nifAutorPrincipal, String propietario) {
       this.isbn = isbn;
       this.titulo = titulo;
       this.portada = portada;
       this.fechaPublicacion = fechaPublicacion;
       this.precio = precio;
       this.nifAutorPrincipal = nifAutorPrincipal;
       this.propietario = propietario;
    }
   
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getPortada() {
        return this.portada;
    }
    
    public void setPortada(String portada) {
        this.portada = portada;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public String getNifAutorPrincipal() {
        return this.nifAutorPrincipal;
    }
    
    public void setNifAutorPrincipal(String nifAutorPrincipal) {
        this.nifAutorPrincipal = nifAutorPrincipal;
    }
    public String getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(String propietario) {
        this.propietario = propietario;
    }




}


